#! /bin/bash
# postinst script
#

set -e

case "$1" in
	configure)
        . /usr/share/apache2/apache2-maintscript-helper
        apache2_reload restart
	;;

	abort-upgrade|abort-remove|abort-deconfigure)

	;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac