#! /bin/bash
# postinst script
#

set -e

case "$1" in
	configure)

		if [ -f /etc/apache2/conf.d/alternc-certbot.conf ]; then
			rm /etc/apache2/conf.d/alternc-certbot.conf
		fi

		if [ -e /usr/share/apache2/apache2-maintscript-helper ]; then
			#Jessie, Stretch
			ln -sf /etc/alternc/alternc-acme.conf /etc/apache2/conf-available/alternc-acme.conf
			. /usr/share/apache2/apache2-maintscript-helper
			apache2_invoke enconf alternc-acme > /dev/null 2>&1 || true
		else
			#Wheezy
			ln -s /etc/alternc/alternc-acme.conf /etc/apache2/conf.d/alternc-acme.conf
			invoke-rc.d apache2 force-reload > /dev/null 2>&1 || true
		fi

		chmod 744 /etc/cron.d/alternc-acme

		echo -e "\033[31m**********************************************"
	    echo "*                                            *"
	    echo "*   ALTERNC          ACTION REQUESTED        *"
	    echo "*                                            *"
	    echo "* Please :                                   *"
	    echo "*   run alternc.install to fully update      *"
	    echo "*   update your ssl quota from admin panel   *"
	    echo "*                                            *"
	    echo "**********************************************"
	    echo -e "\033[0m"

	;;

	abort-upgrade|abort-remove|abort-deconfigure)

	;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

#DEBHELPER#
