#!/usr/bin/php
<?php

chdir("/usr/share/alternc/panel/");
require("/usr/share/alternc/panel/class/config_nochk.php");

// Super admin enabled
$admin->enabled=1;

if ($argv[1] == "dns_reload_zone" && !empty($argv[2])) {
    $domain_name = $argv[2];
    $db->query('select id, compte from domaines where domaine = ?',
               array($domain_name));
    if (!$db->next_record()) {
        $err->log('certbot', 'reload.d - dns_reload_z<one - Unable to find domain information for ' . $domain_name);
        exit -1;
    }
    $mem->su($db->f('compte'));

    $dom->lock();
    $certbot->import($domain_name);
    $dom->unlock();

    $mem->unsu();
}
