#!/bin/bash

## Load Alternc variable
. /etc/alternc/local.sh
## Load debconf
. /usr/share/debconf/confmodule

if [ $1 == "apache2" ]; then
    db_get alternc-certbot/mail
    MAIL="$RET"

    if certbot --agree-tos --email "$MAIL" --non-interactive --apache certonly -d "$FQDN"
    then
        cat "/etc/letsencrypt/live/$FQDN/privkey.pem" > /etc/alternc/apache.pem
        cat "/etc/letsencrypt/live/$FQDN/fullchain.pem" >> /etc/alternc/apache.pem
    fi
fi