#!/bin/bash

## Load Alternc variable
. /etc/alternc/local.sh

if [ "$1" == "apache2" ]; then

    MAIL="admin@$FQDN"

    if [ ! -d /var/lib/letsencrypt/ ]; then
        mkdir /var/lib/letsencrypt/
    fi

    ##Generate let's encrypt certificate
    /usr/lib/alternc/generate_certbot.php --verbose
fi
